In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
dframe = pd.read_csv('2018_Building_Energy_Benchmarking.csv')

In [3]:
dframe

,OSEBuildingID,DataYear,BuildingName,BuildingType,TaxParcelIdentificationNumber,Address,City,State,ZipCode,Latitude,...,ThirdLargestPropertyUseTypeGFA,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),SteamUse(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,ComplianceStatus,ComplianceIssue
0,1,2018,MAYFLOWER PARK HOTEL,NonResidential,0659000030,405 OLIVE WAY,SEATTLE,WA,98101.0,47.61220,...,NaN,1145355.0,3907951.0,14101.0,1410145.0,2090193.0,196.4,2.2,Compliant,No Issue
1,2,2018,PARAMOUNT HOTEL,NonResidential,0659000220,724 PINE ST,SEATTLE,WA,98101.0,47.61317,...,4622.0,840157.0,2866615.0,50307.0,5030730.0,0.0,274.8,3.1,Compliant,No Issue
2,3,2018,WESTIN HOTEL (Parent Building),NonResidential,0659000475,1900 5TH AVE,SEATTLE,WA,98101.0,47.61393,...,0.0,13028620.0,44453651.0,14503.0,1450300.0,20851598.0,1304.2,1.7,Compliant,No Issue
3,5,2018,HOTEL MAX,NonResidential,0659000640,620 STEWART ST,SEATTLE,WA,98101.0,47.61412,...,NaN,769653.0,2626057.0,27306.0,2730608.0,2003570.0,258.5,4.2,Compliant,No Issue
4,8,2018,WARWICK SEATTLE HOTEL,NonResidential,0659000970,401 LENORA ST,SEATTLE,WA,98121.0,47.61375,...,0.0,1392492.0,4751183.0,83829.0,8382912.0,0.0,457.9,4.0,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3532,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118.0,47.53771,...,NaN,625138.0,2132970.0,26767.0,2676660.0,0.0,147.9,0.4,Compliant,No Issue
3533,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106.0,47.54657,...,34255.0,1543452.0,5266258.0,0.0,0.0,0.0,14.1,0.0,Compliant,No Issue
3534,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119.0,47.63100,...,143000.0,21549590.0,73527201.0,31671.0,3167104.0,0.0,364.5,0.4,Compliant,No Issue
3535,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106.0,47.57250,...,33420.0,3939839.0,13442731.0,2191.0,219138.0,0.0,47.5,0.2,Compliant,No Issue
3536,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119.0,47.62660,...,6823.0,5997937.0,20464961.0,0.0,0.0,0.0,54.6,0.8,Compliant,No Issue

In [4]:
dframe = pd.read_csv('2018_Building_Energy_Benchmarking.csv', header = None)

In [5]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,OSEBuildingID,DataYear,BuildingName,BuildingType,TaxParcelIdentificationNumber,Address,City,State,ZipCode,Latitude,...,ThirdLargestPropertyUseTypeGFA,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),SteamUse(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,ComplianceStatus,ComplianceIssue
1,1,2018,MAYFLOWER PARK HOTEL,NonResidential,0659000030,405 OLIVE WAY,SEATTLE,WA,98101,47.6122,...,NaN,1145355,3907951,14101,1410145,2090193,196.4,2.2,Compliant,No Issue
2,2,2018,PARAMOUNT HOTEL,NonResidential,0659000220,724 PINE ST,SEATTLE,WA,98101,47.61317,...,4622,840157,2866615,50307,5030730,0,274.8,3.1,Compliant,No Issue
3,3,2018,WESTIN HOTEL (Parent Building),NonResidential,0659000475,1900 5TH AVE,SEATTLE,WA,98101,47.61393,...,0,13028620,44453651,14503,1450300,20851598,1304.2,1.7,Compliant,No Issue
4,5,2018,HOTEL MAX,NonResidential,0659000640,620 STEWART ST,SEATTLE,WA,98101,47.61412,...,NaN,769653,2626057,27306,2730608,2003570,258.5,4.2,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [6]:
dframe.fillna('NaN', inplace=True)

In [7]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,OSEBuildingID,DataYear,BuildingName,BuildingType,TaxParcelIdentificationNumber,Address,City,State,ZipCode,Latitude,...,ThirdLargestPropertyUseTypeGFA,Electricity(kWh),Electricity(kBtu),NaturalGas(therms),NaturalGas(kBtu),SteamUse(kBtu),TotalGHGEmissions,GHGEmissionsIntensity,ComplianceStatus,ComplianceIssue
1,1,2018,MAYFLOWER PARK HOTEL,NonResidential,0659000030,405 OLIVE WAY,SEATTLE,WA,98101,47.6122,...,NaN,1145355,3907951,14101,1410145,2090193,196.4,2.2,Compliant,No Issue
2,2,2018,PARAMOUNT HOTEL,NonResidential,0659000220,724 PINE ST,SEATTLE,WA,98101,47.61317,...,4622,840157,2866615,50307,5030730,0,274.8,3.1,Compliant,No Issue
3,3,2018,WESTIN HOTEL (Parent Building),NonResidential,0659000475,1900 5TH AVE,SEATTLE,WA,98101,47.61393,...,0,13028620,44453651,14503,1450300,20851598,1304.2,1.7,Compliant,No Issue
4,5,2018,HOTEL MAX,NonResidential,0659000640,620 STEWART ST,SEATTLE,WA,98101,47.61412,...,NaN,769653,2626057,27306,2730608,2003570,258.5,4.2,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [8]:
ENERGYSTARSCore_index = dframe[dframe[22] == 'NaN']

In [9]:
ENERGYSTARSCore_index

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
89,135,2018,CERTAINTEED WAREHOUSE,NonResidential,1924049092,5931 E MARGINAL WAY S,SEATTLE,WA,98134,47.54854,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
95,141,2018,HUGHES ELEMENTARY SCHOOL - Under Construction ...,SPS-District K-12,1932300245,7740 34TH AVE SW,SEATTLE,WA,98126,47.53284,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
130,215,2018,RAINIER BOTTLING PLANT,NonResidential,3466800065,5628 AIRPORT WAY S,SEATTLE,WA,98108,47.55152,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
146,237,2018,WHITTIER ELEMENTARY (SPS-DISTRICT),SPS-District K-12,4240400005,7501 13TH AVE NW,SEATTLE,WA,98117,47.68359,...,NaN,479328,1635466,0,0,0,4.4,0.1,Not Compliant,Missing EUI or Electricity Data
150,242,2018,OLYMPIC VIEW (SPS-DISTRICT),SPS-District K-12,5100404840,504 NE 95TH ST,SEATTLE,WA,98115,47.69823,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3511,50336,2018,TWENTY 20 MAD APARTMENTS,Multifamily MR (5-9),9497700010,2020 E MADISON ST,SEATTLE,WA,NaN,0,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
3513,50338,2018,HARLOW HEIGHTS,Multifamily LR (1-4),3679400970,4351 15TH AVE S,SEATTLE,WA,NaN,47.56382,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
3515,50341,2018,VEGA APARTMENTS,Multifamily MR (5-9),3389900195,4528 44TH AVE SW,SEATTLE,WA,NaN,47.56204,...,NaN,0,0,4069,406898,0,21.6,0.9,Not Compliant,Missing EUI or Electricity Data
3518,50344,2018,ORI APARTMENTS,Multifamily MR (5-9),8816400685,5260 UNIVERSITY WAY NE,SEATTLE,WA,NaN,47.66749,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...
3524,50351,2018,STREAM 403,Multifamily MR (5-9),6848200476,403 BELMONT AVE E,SEATTLE,WA,NaN,47.62257,...,NaN,0,0,0,0,0,0,0,Not Compliant,Portfolio Manager Not Connected to the City of...

In [10]:
dframe.drop(ENERGYSTARSCore_index, inplace= True)

In [11]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
42,56,2018,HILTON SEATTLE,NonResidential,7802920020,1301 6TH AVE,SEATTLE,WA,98101,47.60946,...,NaN,2689945,9178092,62538,6253815,0,356.6,2.8,Compliant,No Issue
43,57,2018,5TH & PINE,NonResidential,1975700200,1513 5TH AVE,SEATTLE,WA,98101,47.6113,...,493,2671369,9114711,0,0,0,24.3,0.1,Compliant,No Issue
44,58,2018,CENTURY SQUARE RETAIL,NonResidential,1975700365,1525 4TH AVE,SEATTLE,WA,98101,47.61076,...,NaN,195653,667569,3756,375626,0,21.7,0.4,Compliant,No Issue
45,59,2018,GIBRALTAR TOWER,NonResidential,1975700380,1518 3RD AVE,SEATTLE,WA,98101,47.61048,...,NaN,761963,2599818,0,0,0,6.9,0.1,Compliant,No Issue
46,60,2018,MANN BUILDING/WILD GINGER/TRIPLE DOOR,NonResidential,1975700525,1401 3RD AVE,SEATTLE,WA,98101,47.60886,...,5459,1338469,4566856,110816,11081570,0,600.7,11.4,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [12]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
42,56,2018,HILTON SEATTLE,NonResidential,7802920020,1301 6TH AVE,SEATTLE,WA,98101,47.60946,...,NaN,2689945,9178092,62538,6253815,0,356.6,2.8,Compliant,No Issue
43,57,2018,5TH & PINE,NonResidential,1975700200,1513 5TH AVE,SEATTLE,WA,98101,47.6113,...,493,2671369,9114711,0,0,0,24.3,0.1,Compliant,No Issue
44,58,2018,CENTURY SQUARE RETAIL,NonResidential,1975700365,1525 4TH AVE,SEATTLE,WA,98101,47.61076,...,NaN,195653,667569,3756,375626,0,21.7,0.4,Compliant,No Issue
45,59,2018,GIBRALTAR TOWER,NonResidential,1975700380,1518 3RD AVE,SEATTLE,WA,98101,47.61048,...,NaN,761963,2599818,0,0,0,6.9,0.1,Compliant,No Issue
46,60,2018,MANN BUILDING/WILD GINGER/TRIPLE DOOR,NonResidential,1975700525,1401 3RD AVE,SEATTLE,WA,98101,47.60886,...,5459,1338469,4566856,110816,11081570,0,600.7,11.4,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [13]:
type(dframe)

pandas.core.frame.DataFrame

In [14]:
dframe = dframe.loc[~dframe[2].str.contains('CENTER'), :]

In [15]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
42,56,2018,HILTON SEATTLE,NonResidential,7802920020,1301 6TH AVE,SEATTLE,WA,98101,47.60946,...,NaN,2689945,9178092,62538,6253815,0,356.6,2.8,Compliant,No Issue
43,57,2018,5TH & PINE,NonResidential,1975700200,1513 5TH AVE,SEATTLE,WA,98101,47.6113,...,493,2671369,9114711,0,0,0,24.3,0.1,Compliant,No Issue
44,58,2018,CENTURY SQUARE RETAIL,NonResidential,1975700365,1525 4TH AVE,SEATTLE,WA,98101,47.61076,...,NaN,195653,667569,3756,375626,0,21.7,0.4,Compliant,No Issue
45,59,2018,GIBRALTAR TOWER,NonResidential,1975700380,1518 3RD AVE,SEATTLE,WA,98101,47.61048,...,NaN,761963,2599818,0,0,0,6.9,0.1,Compliant,No Issue
46,60,2018,MANN BUILDING/WILD GINGER/TRIPLE DOOR,NonResidential,1975700525,1401 3RD AVE,SEATTLE,WA,98101,47.60886,...,5459,1338469,4566856,110816,11081570,0,600.7,11.4,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [ ]:
# BuildingNameContains_center = dframe[dframe[2].str.contains('CENTER')]

In [ ]:
# BuildingNameContains_center

In [ ]:
# YearBuilt_convert_to_integer = dframe[13].astype(int)

In [ ]:
# YearBuilt_less_than_1920 = YearBuilt_convert_to_integer < 1920

In [ ]:
# YearBuilt_less_than_1920

In [16]:
# dframe.drop(YearBuilt_less_than_1920, inplace=True)
# dframe = dframe.loc[~dframe[13].astype(int)<1920, :]
dframe=dframe[np.invert(dframe.loc[:,13].astype(int)<1920)]

In [17]:
dframe

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
42,56,2018,HILTON SEATTLE,NonResidential,7802920020,1301 6TH AVE,SEATTLE,WA,98101,47.60946,...,NaN,2689945,9178092,62538,6253815,0,356.6,2.8,Compliant,No Issue
43,57,2018,5TH & PINE,NonResidential,1975700200,1513 5TH AVE,SEATTLE,WA,98101,47.6113,...,493,2671369,9114711,0,0,0,24.3,0.1,Compliant,No Issue
44,58,2018,CENTURY SQUARE RETAIL,NonResidential,1975700365,1525 4TH AVE,SEATTLE,WA,98101,47.61076,...,NaN,195653,667569,3756,375626,0,21.7,0.4,Compliant,No Issue
46,60,2018,MANN BUILDING/WILD GINGER/TRIPLE DOOR,NonResidential,1975700525,1401 3RD AVE,SEATTLE,WA,98101,47.60886,...,5459,1338469,4566856,110816,11081570,0,600.7,11.4,Compliant,No Issue
47,62,2018,ROOSEVELT HOTEL (HOTEL THEODORE),NonResidential,1976700010,1531 7TH AVE,SEATTLE,WA,98101,47.61233,...,7057,1379876,4708137,8080,807954,2075751,165.8,1.9,Compliant,No Issue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3533,50414,2018,OTHELLO NORTH,Multifamily MR (5-9),8800000035,4200 S OTHELLO ST,SEATTLE,WA,98118,47.53771,...,NaN,625138,2132970,26767,2676660,0,147.9,0.4,Compliant,No Issue
3534,50415,2018,PORT OF SEATTLE- TERMINAL 115 (CAMPUS),Campus,5367202505,6000 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.54657,...,34255,1543452,5266258,0,0,0,14.1,0,Compliant,No Issue
3535,50416,2018,PORT OF SEATTLE- TERMINAL 91 (CAMPUS),Campus,7666201146,2001 W GARFIELD ST,SEATTLE,WA,98119,47.631,...,143000,21549590,73527201,31671,3167104,0,364.5,0.4,Compliant,No Issue
3536,50452,2018,PORT OF SEATTLE - TERMINAL 5 CAMPUS,Campus,7666705565,3443 WEST MARGINAL WAY SW,SEATTLE,WA,98106,47.5725,...,33420,3939839,13442731,2191,219138,0,47.5,0.2,Compliant,No Issue
3537,50453,2018,PORT OF SEATTLE - TERMINAL 86,Campus,7666202055,955 ALASKAN WAY W,SEATTLE,WA,98119,47.6266,...,6823,5997937,20464961,0,0,0,54.6,0.8,Compliant,No Issue

In [19]:
dframe.loc[dframe[15].idxmax()]

TypeError: reduction operation 'argmax' not allowed for this dtype

In [20]:
ENERGYSTARScore_over_97 = dframe[dframe[20] >=97]

TypeError: '>=' not supported between instances of 'str' and 'int'